---
abstract: 'TheEye is a TAP based monitoring system'
author:
  - 'Lenz Gschwendtner <lenz@springtimesoft.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TheEye
requires:
  Collectd::Unixsock: 0
  Data::Dumper: 0
  File::ShareDir: 0
  File::Util: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  Mouse: 0
  Mouse::Role: 0
  POSIX: 0
  RRD::Simple: 0
  Riemann::Client: 0
  Sys::Hostname: 0
  TAP::Parser: 0
  TAP::Parser::Aggregator: 0
  Time::HiRes: 0
  URI::Escape: 0
  XML::Simple: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/norbu09/TheEye.git
version: 0.8
